# syntax=docker/dockerfile:1
# check=error=true

FROM node:24.1.0-alpine3.21 AS build-stage
WORKDIR /usr/app
COPY . .
RUN npm install && npm run build

FROM nginx:1.27.5-alpine3.21 AS production-stage
COPY --from=build-stage /usr/app/dist /usr/share/nginx/html
COPY .nginx/production.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
