export const Errors = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT: 'RATE_LIMIT',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  CONFLICT: 'CONFLICT',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
  INVALID_REFRESH: 'INVALID_REFRESH',
  EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
  RESET_TOKEN_ALREADY_USED: 'RESET_TOKEN_ALREADY_USED',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  RESET_TOKEN_NOT_FOUND: 'RESET_TOKEN_NOT_FOUND',

  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  ACCESS_TOKEN_NOT_FOUND: 'ACCESS_TOKEN_NOT_FOUND',
} as const

export type ErrorKey = keyof typeof Errors
export type ErrorValue = (typeof Errors)[ErrorKey]
